List data = [
  {"name": "5 Star Chocolate"},
  {"name": "7Days"},
  {"name": "7Up"},
  {"name": "Apple"},
  {"name": "AirBnB"},
  {"name": "Arsenal FC"},
  {"name": "ALDO"},
  {"name": "Arket"},
  {"name": "Axe"},
  {"name": "Accenture"},
  {"name": "Ariel"},
  {"name": "Adidas"},
  {"name": "ASDA"},
  {"name": "ActionIQ"},
  {"name": "Aquafina"},
  {"name": "Amika"},
  {"name": "AccuWeather"},
  {"name": "Activia"},
  {"name": "Adobe"},
  {"name": "Amazon Kindle"},
  {"name": "Aesop"},
  {"name": "Azrieli Group"},
  {"name": "American Eagle"},
  {"name": "Amway Corp"},
  {"name": "Amazon"},
  {"name": "Ahava"},
  {"name": "Axel Springer"},
  {"name": "American Airlines"},
  {"name": "American Express"},
  {"name": "Atlassian"},
  {"name": "Axa"},
  {"name": "AdeS"},
  {"name": "Aquarius"},
  {"name": "Ayataka"},
  {"name": "Audi"},
  {"name": "Barqs"},
  {"name": "Bain & Company"},
  {"name": "Bayer"},
  {"name": "Bank Leumi"},
  {"name": "Bank Hapoalim"},
  {"name": "Baskin robin"},
  {"name": "Bounty"},
  {"name": "Burger King"},
  {"name": "BCG (Boston Consulting Group)"},
  {"name": "Biotherm"},
  {"name": "Bershka"},
  {"name": "Bloomberg"},
  {"name": "BMW"},
  {"name": "Boeing"},
  {"name": "Booz Allen Hamilton"},
  {"name": "Burberry"},
  {"name": "Bath & Body Works"},
  {"name": "Bosch"},
  {"name": "Bristol Myers Squibb"},
  {"name": "Capri Holdings"},
  {"name": "Costa"},
  {"name": "Carita Paris"},
  {"name": "CareTrust REIT"},
  {"name": "Caterpillar"},
  {"name": "Caltex"},
  {"name": "CNN"},
  {"name": "Coach"},
  {"name": "Cappy"},
  {"name": "Caudalie"},
  {"name": "CeraVe"},
  {"name": "Check Point Software Technologies"},
  {"name": "Cerelac"},
  {"name": "Chanel"},
  {"name": "Chapman and Cutler"},
  {"name": "Channel"},
  {"name": "Cheerios"},
  {"name": "Cheetos"},
  {"name": "Careline"},
  {"name": "Chevron"},
  {"name": "Chips Ahoy!"},
  {"name": "Christina Aguilera"},
  {"name": "Citi Bank"},
  {"name": "Carrefour"},
  {"name": "Codral"},
  {"name": "Cosco"},
  {"name": "Canada Dry"},
  {"name": "Citi"},
  {"name": "Clal Insurance Enterprises"},
  {"name": "Clean & Clear"},
  {"name": "Clearblue"},
  {"name": "Clinique"},
  {"name": "Champion"},
  {"name": "Club Social"},
  {"name": "Coca Cola"},
  {"name": "Coke"},
  {"name": "Coffee Mate"},
  {"name": "Colgate"},
  {"name": "Comcast"},
  {"name": "Compass"},
  {"name": "Caesars"},
  {"name": "Conde Nast"},
  {"name": "Cooley LLP"},
  {"name": "Costco"},
  {"name": "Côte d’Or"},
  {"name": "Crest"},
  {"name": "CV Starr"},
  {"name": "CyberArk Software"},
  {"name": "Cytokinetics"},
  {"name": "Crayola"},
  {"name": "Cra Z Art"},
  {"name": "Daimler"},
  {"name": "Dr Pepper"},
  {"name": "Del Valle"},
  {"name": "Daim"},
  {"name": "Doctor Pepper"},
  {"name": "Dasani"},
  {"name": "Doritos"},
  {"name": "Dove"},
  {"name": "Daz"},
  {"name": "Dior"},
  {"name": "Dell"},
  {"name": "Deloitte"},
  {"name": "Delta Air Lines"},
  {"name": "Deutsche Bank"},
  {"name": "Deutsche Telekom"},
  {"name": "DHL Group"},
  {"name": "Donutelier"},
  {"name": "David Off"},
  {"name": "Disney"},
  {"name": "DLA Piper"},
  {"name": "Domestos"},
  {"name": "Domino’s"},
  {"name": "Douglas Elliman"},
  {"name": "Downy"},
  {"name": "Dr. Fischer"},
  {"name": "Doctor Or"},
  {"name": "Duane Morris LLP"},
  {"name": "Dreft Baby Detergent & Laundry Products"},
  {"name": "Dreyer’s Grand Ice Cream"},
  {"name": "eBay"},
  {"name": "Edelman"},
  {"name": "Eli Lilly"},
  {"name": "Evian"},
  {"name": "Empyrean"},
  {"name": "Energizer"},
  {"name": "Ericsson"},
  {"name": "Endeavor"},
  {"name": "EPAM Systems"},
  {"name": "Estee Lauder"},
  {"name": "Elbit Systems"},
  {"name": "Expedia"},
  {"name": "EY"},
  {"name": "Forbes"},
  {"name": "Facebook"},
  {"name": "Fairlife"},
  {"name": "Fonterra"},
  {"name": "Fanta"},
  {"name": "Ford"},
  {"name": "First International Bank of Israel"},
  {"name": "Fiverr"},
  {"name": "Funyuns"},
  {"name": "Fuze"},
  {"name": "Fox News"},
  {"name": "Fritos"},
  {"name": "Fox Corp"},
  {"name": "Gatorade"},
  {"name": "Gamida Cell"},
  {"name": "GE"},
  {"name": "Gillette"},
  {"name": "Glamglow"},
  {"name": "General Catalyst"},
  {"name": "General Motors"},
  {"name": "Georgia"},
  {"name": "Gold Peak"},
  {"name": "Genesys"},
  {"name": "Goldman Sachs"},
  {"name": "Grandma’s Cookies"},
  {"name": "Google"},
  {"name": "GA-DE cosmetics"},
  {"name": "Garnier"},
  {"name": "Guess"},
  {"name": "Greenberg Traurig"},
  {"name": "Guerlain"},
  {"name": "Givenchy"},
  {"name": "Glaxo Smith Kline (GSK)"},
  {"name": "H&M"},
  {"name": "Hadiklaim"},
  {"name": "Hardees"},
  {"name": "Huggies"},
  {"name": "Hanes"},
  {"name": "HSBC"},
  {"name": "Head & Shoulders"},
  {"name": "Hersheys"},
  {"name": "Herbert Smith Freehills"},
  {"name": "Hewlett Packard"},
  {"name": "Hasbro"},
  {"name": "Hyundai"},
  {"name": "Henkel"},
  {"name": "Harel Insurance Investment & Financial Services"},
  {"name": "Hewlett Packard Enterprise"},
  {"name": "HubSpot"},
  {"name": "Huntsman Corp"},
  {"name": "Hp"},
  {"name": "IBM"},
  {"name": "Innocent"},
  {"name": "Insight Partners"},
  {"name": "Inditex Group"},
  {"name": "IT Cosmetics"},
  {"name": "Instacart"},
  {"name": "Intel"},
  {"name": "Irish Spring"},
  {"name": "Intermedia"},
  {"name": "Interpublic Group"},
  {"name": "Instagram"},
  {"name": "ICL Group"},
  {"name": "Intuit"},
  {"name": "Jazwares"},
  {"name": "Jefferies"},
  {"name": "John Lewis"},
  {"name": "JP Morgan Chase"},
  {"name": "Jaguar"},
  {"name": "Johnson & Johnson"},
  {"name": "JPMorgan"},
  {"name": "Kenon Holdings"},
  {"name": "Kate Spade"},
  {"name": "Kirks’"},
  {"name": "Kinley Water"},
  {"name": "Kitkat"},
  {"name": "KKR"},
  {"name": "KFC"},
  {"name": "KKW Cosmetics"},
  {"name": "Kurkure"},
  {"name": "Keebler"},
  {"name": "Kolynos"},
  {"name": "Kaufland"},
  {"name": "Kevita"},
  {"name": "Knorr"},
  {"name": "KPMG"},
  {"name": "Kiko Milano"},
  {"name": "Lays"},
  {"name": "Lemonade"},
  {"name": "Lidl"},
  {"name": "Loblaws"},
  {"name": "Levi Strauss"},
  {"name": "Louis Vuitton"},
  {"name": "Life Water"},
  {"name": "Levi’s"},
  {"name": "Levi’s Strauss"},
  {"name": "LinkedIn"},
  {"name": "Land Rover"},
  {"name": "L’Oréal"},
  {"name": "Lego"},
  {"name": "Levissima"},
  {"name": "Live Nation Entertainment"},
  {"name": "Lufthansa"},
  {"name": "La Roche-Posay"},
  {"name": "Lipton"},
  {"name": "Lifebuoy"},
  {"name": "Major League Baseball"},
  {"name": "Manpower Group"},
  {"name": "Maggie"},
  {"name": "Mars"},
  {"name": "Marriott"},
  {"name": "Marsh McLennan"},
  {"name": "Maison Francis Kurkdjian"},
  {"name": "Mastercard"},
  {"name": "Mattel"},
  {"name": "Minute Maid"},
  {"name": "Monster"},
  {"name": "Monki"},
  {"name": "Mainz FC"},
  {"name": "Mellow Yellow"},
  {"name": "Mountain Dew"},
  {"name": "Moroccan Oil"},
  {"name": "Migdal Insurance"},
  {"name": "Marks & Spencer"},
  {"name": "Mirinda"},
  {"name": "McDermott Will & Emery"},
  {"name": "McDonald’s"},
  {"name": "Motorola"},
  {"name": "McKinsey"},
  {"name": "Merck"},
  {"name": "Michael Kors"},
  {"name": "Milo"},
  {"name": "Mizrahi Tefahot Bank"},
  {"name": "Merck KGaA"},
  {"name": "Micheal Kors"},
  {"name": "Milkybar"},
  {"name": "Maybelline"},
  {"name": "Mount Franklin"},
  {"name": "Meta"},
  {"name": "MeUndies"},
  {"name": "Mattle"},
  {"name": "Microsoft"},
  {"name": "Munchies"},
  {"name": "Miranda"},
  {"name": "Morgan Lewis"},
  {"name": "Motorola"},
  {"name": "Moroccanoil"},
  {"name": "Morgan Stanley"},
  {"name": "MRC"},
  {"name": "Nasdaq"},
  {"name": "Naughty Dog"},
  {"name": "Nivea"},
  {"name": "Next"},
  {"name": "NOS"},
  {"name": "Nabisco"},
  {"name": "Nutter Butter"},
  {"name": "No Frills"},
  {"name": "National Basketball Association"},
  {"name": "National Geographic"},
  {"name": "Nintendo"},
  {"name": "New Balance"},
  {"name": "Nutella"},
  {"name": "Newtons"},
  {"name": "NVIDIA"},
  {"name": "Netflix"},
  {"name": "Nescafe"},
  {"name": "Nestle"},
  {"name": "Nesquick"},
  {"name": "Nike"},
  {"name": "Nokia"},
  {"name": "Nussbeisser"},
  {"name": "Oreo"},
  {"name": "Oral B"},
  {"name": "Old spice"},
  {"name": "Oysho"},
  {"name": "Omeprazole"},
  {"name": "Oceanspray"},
  {"name": "Opodo"},
  {"name": "P&G (Procter and Gamble)"},
  {"name": "Pampers"},
  {"name": "Pull & Bear"},
  {"name": "Pepsi"},
  {"name": "Pfizer"},
  {"name": "Popeyes"},
  {"name": "Parker Pens"},
  {"name": "Philadelphia Cream Cheese"},
  {"name": "Pizza Hut"},
  {"name": "Powerade"},
  {"name": "Purina"},
  {"name": "Phoenix Holdings"},
  {"name": "Propel"},
  {"name": "Ponds"},
  {"name": "Pure Leaf Green Tea"},
  {"name": "Power Action Wipes"},
  {"name": "PwC"},
  {"name": "Prada"},
  {"name": "Perry Ellis"},
  {"name": "Prada Eyewear"},
  {"name": "Pringles"},
  {"name": "Payoneer"},
  {"name": "Palmolive"},
  {"name": "Procter & Gamble"},
  {"name": "Purelife"},
  {"name": "Pureology"},
  {"name": "PUM"},
  {"name": "Puma"},
  {"name": "Revlon"},
  {"name": "Siemens"},
  {"name": "Snickers"},
  {"name": "Sprite"},
  {"name": "Starbucks"},
  {"name": "Subway"},
  {"name": "Tang"},
  {"name": "Tide"},
  {"name": "Toblerone"},
  {"name": "Twix"},
  {"name": "Victoria’s secret"},
  {"name": "Vim"},
  {"name": "Walls"},
  {"name": "Walmart"},
  {"name": "Wix"}
];
